package ru.greeneyes.project.pomidoro.modalwindow;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import static java.awt.event.KeyEvent.VK_ESCAPE;

/**
 * User: dima
 * Date: Nov 29, 2010
 */
class ModalForm {
	// TODO move to resources
	private static final String TEXT = "To unlock, click on pomodoro picture % times and press ESC. (Double-clicks don't count.)";

	public JPanel rootPanel;
	private JLabel pomodoroPicture;
	private JLabel messageLabel;
	private final FormModel model;

	public ModalForm(final FormModel model, final Window jDialog) {
		this.model = model;

		$$$setupUI$$$();
		pomodoroPicture.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent mouseEvent) {
				if (mouseEvent.getClickCount() == 1) {
					model.userClick();
					updateUI();
				}
			}
		});
		pomodoroPicture.addKeyListener(new KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent keyEvent) {
				boolean pressedEscape = (keyEvent.getKeyCode() == VK_ESCAPE) && (keyEvent.getModifiers() == 0);
				if (pressedEscape && model.dialogIsAllowedToBeClosed()) {
					jDialog.dispose();
				}
			}
		});
	}

	private void createUIComponents() {
		messageLabel = new JLabel();
		updateUI();
	}

	private void updateUI() {
		messageLabel.setToolTipText(TEXT.replace("%", String.valueOf(model.clicksLeft())));
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		rootPanel = new JPanel();
		rootPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
		pomodoroPicture = new JLabel();
		pomodoroPicture.setEnabled(true);
		pomodoroPicture.setFocusable(true);
		pomodoroPicture.setIcon(new ImageIcon(getClass().getResource("/resources/1.png")));
		pomodoroPicture.setText("");
		rootPanel.add(pomodoroPicture, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 1, new Insets(5, 0, 10, 0), -1, -1));
		rootPanel.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		messageLabel.setHorizontalTextPosition(11);
		messageLabel.setText("IntelliJ is blocked until the end of break.");
		panel1.add(messageLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rootPanel;
	}
}
